# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 23:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DirtyDrive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDistrict',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
